/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestSyncpayRouteImport } from './routes/api/test-syncpay'
import { Route as ApiCreatePixRouteImport } from './routes/api/create-pix'
import { Route as ApiCheckPaymentRouteImport } from './routes/api/check-payment'
import { Route as ApiPublicUtmifyTestRouteImport } from './routes/api/public/utmify-test'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSyncpayRoute = ApiTestSyncpayRouteImport.update({
  id: '/api/test-syncpay',
  path: '/api/test-syncpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePixRoute = ApiCreatePixRouteImport.update({
  id: '/api/create-pix',
  path: '/api/create-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckPaymentRoute = ApiCheckPaymentRouteImport.update({
  id: '/api/check-payment',
  path: '/api/check-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUtmifyTestRoute = ApiPublicUtmifyTestRouteImport.update({
  id: '/api/public/utmify-test',
  path: '/api/public/utmify-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vip': typeof VipRoute
  '/api/check-payment': typeof ApiCheckPaymentRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/test-syncpay': typeof ApiTestSyncpayRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/utmify-test': typeof ApiPublicUtmifyTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vip': typeof VipRoute
  '/api/check-payment': typeof ApiCheckPaymentRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/test-syncpay': typeof ApiTestSyncpayRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/utmify-test': typeof ApiPublicUtmifyTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vip': typeof VipRoute
  '/api/check-payment': typeof ApiCheckPaymentRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/test-syncpay': typeof ApiTestSyncpayRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/utmify-test': typeof ApiPublicUtmifyTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vip'
    | '/api/check-payment'
    | '/api/create-pix'
    | '/api/test-syncpay'
    | '/api/public/mp-webhook'
    | '/api/public/utmify-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vip'
    | '/api/check-payment'
    | '/api/create-pix'
    | '/api/test-syncpay'
    | '/api/public/mp-webhook'
    | '/api/public/utmify-test'
  id:
    | '__root__'
    | '/'
    | '/vip'
    | '/api/check-payment'
    | '/api/create-pix'
    | '/api/test-syncpay'
    | '/api/public/mp-webhook'
    | '/api/public/utmify-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VipRoute: typeof VipRoute
  ApiCheckPaymentRoute: typeof ApiCheckPaymentRoute
  ApiCreatePixRoute: typeof ApiCreatePixRoute
  ApiTestSyncpayRoute: typeof ApiTestSyncpayRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicUtmifyTestRoute: typeof ApiPublicUtmifyTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-syncpay': {
      id: '/api/test-syncpay'
      path: '/api/test-syncpay'
      fullPath: '/api/test-syncpay'
      preLoaderRoute: typeof ApiTestSyncpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-pix': {
      id: '/api/create-pix'
      path: '/api/create-pix'
      fullPath: '/api/create-pix'
      preLoaderRoute: typeof ApiCreatePixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-payment': {
      id: '/api/check-payment'
      path: '/api/check-payment'
      fullPath: '/api/check-payment'
      preLoaderRoute: typeof ApiCheckPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/utmify-test': {
      id: '/api/public/utmify-test'
      path: '/api/public/utmify-test'
      fullPath: '/api/public/utmify-test'
      preLoaderRoute: typeof ApiPublicUtmifyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VipRoute: VipRoute,
  ApiCheckPaymentRoute: ApiCheckPaymentRoute,
  ApiCreatePixRoute: ApiCreatePixRoute,
  ApiTestSyncpayRoute: ApiTestSyncpayRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicUtmifyTestRoute: ApiPublicUtmifyTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
